DPT_balance_color: ClassDefine.o WindowSet.o DisjointSet.o ScanLine.o IOInterface.o  Factors.o WinPri.o Coloring.o main.o
	g++ -O2 -std=c++11 -w -o DPT_balance_color ClassDefine.o WindowSet.o DisjointSet.o ScanLine.o IOInterface.o  Factors.o WinPri.o Coloring.o main.o
main.o: main.cpp ClassDefine.h DisjointSet.h ScanLine.h WindowSet.h IOInterface.h Factors.h WinPri.h Coloring.h
	g++ -O2 -std=c++11 -w -c main.cpp
Coloring.o: Coloring.cpp
	g++ -O2 -std=c++11 -w -c Coloring.cpp
WinPri.o: WinPri.cpp
	g++ -O2 -std=c++11 -w -c WinPri.cpp
Factors.o: Factors.cpp
	g++ -O2 -std=c++11 -w -c Factors.cpp
IOInterface.o: IOInterface.cpp
	g++ -O2 -std=c++11 -w -c IOInterface.cpp
ScanLine.o: ScanLine.cpp
	g++ -O2 -std=c++11 -w -c ScanLine.cpp
DisjointSet.o: DisjointSet.cpp
	g++ -O2 -std=c++11 -w -c DisjointSet.cpp
WindowSet.o: WindowSet.cpp
	g++ -O2 -std=c++11 -w -c WindowSet.cpp
ClassDefine.o:ClassDefine.cpp
	g++ -O2 -std=c++11 -w -c ClassDefine.cpp